// Generated by `php artisan make:js-models`. Edit the AppModel $properties, not this file.
import Model from "../vendor/juice/data/models/Model.mjs";

class ContentAsset extends Model {
    static tableName = "content_assets";
    static primaryKey = "id";
    static timestamps = true;

    static get schema() {
        return {
        "user_id": {
            "type": "integer"
        },
        "title": {
            "type": "string",
            "label": "Title"
        },
        "type": {
            "type": "string",
            "label": "Asset type"
        },
        "notes": {
            "type": "string",
            "label": "Notes for ingestion"
        },
        "disk": {
            "type": "string"
        },
        "path": {
            "type": "string"
        },
        "original_filename": {
            "type": "string"
        },
        "mime_type": {
            "type": "string"
        },
        "size": {
            "type": "integer"
        },
        "ingestion_status": {
            "type": "string"
        },
        "ingestion_result": {
            "type": "string"
        }
    };
    }

    static get rules() {
        return {
        "title": "nullable|string|max:255",
        "type": "required|string",
        "notes": "nullable|string|max:2000"
    };
    }
}

export default ContentAsset;
