// Generated by juice/data/models/generate/make.mjs. Edit the source model, not this file.
import Model from "../vendor/juice/data/models/Model.mjs";

class Onboarding extends Model {
    static tableName = "onboardings";
    static primaryKey = "id";
    static timestamps = true;

    static get schema() {
        return {
            "user_id": {
                "type": "integer",
                "fillable": true
            },
            "step": {
                "type": "integer",
                "fillable": true
            },
            "dns_verified": {
                "type": "boolean",
                "fillable": true,
                "cast": "boolean"
            },
            "company_name": {
                "type": "string",
                "fillable": true,
                "label": "Company name"
            },
            "business_category": {
                "type": "string",
                "fillable": true,
                "label": "Business category"
            },
            "slogans": {
                "type": "string",
                "fillable": true,
                "label": "Slogans or taglines"
            },
            "region": {
                "type": "string",
                "fillable": true,
                "label": "Primary location"
            },
            "region_scope": {
                "type": "string",
                "fillable": true,
                "label": "Audience reach"
            },
            "logo": {
                "type": "string",
                "fillable": false,
                "label": "Logo"
            },
            "primary_colors": {
                "type": "json",
                "fillable": true,
                "cast": "array",
                "label": "Primary colors"
            },
            "logo_disk": {
                "type": "string",
                "fillable": true
            },
            "logo_path": {
                "type": "string",
                "fillable": true
            },
            "inspiration_domains": {
                "type": "json",
                "fillable": true,
                "cast": "array"
            },
            "suggested_sites": {
                "type": "json",
                "fillable": true,
                "cast": "array"
            },
            "imports_started_at": {
                "type": "date",
                "fillable": true,
                "cast": "datetime"
            }
        };
    }

    static get rules() {
        return {
            "company_name": "required|string|max:255",
            "business_category": "required|string|max:255",
            "slogans": "nullable|string|max:2000",
            "region": "required|string|max:255",
            "region_scope": "required|in:regional,national"
        };
    }

    static get form() {
        return {
            "company_name": {
                "type": "text",
                "label": "Company name",
                "placeholder": "Your business name",
                "name": "company_name",
                "required": true,
                "validation": "max:255"
            },
            "business_category": {
                "type": "text",
                "label": "Business category",
                "placeholder": "e.g. Italian restaurant, law firm, gym",
                "name": "business_category",
                "required": true,
                "validation": "max:255"
            },
            "slogans": {
                "type": "textarea",
                "label": "Slogans or taglines",
                "help": "Optional — one per line.",
                "name": "slogans",
                "required": false,
                "validation": "max:2000"
            },
            "region": {
                "type": "text",
                "label": "Primary location",
                "placeholder": "e.g. Austin, TX or United States",
                "name": "region",
                "required": true,
                "validation": "max:255"
            },
            "region_scope": {
                "class": "flex:static w:50",
                "type": "select",
                "label": "Audience reach",
                "options": {
                    "Regional / local": "regional",
                    "Countrywide": "national"
                },
                "name": "region_scope",
                "required": true,
                "validation": "in:regional,national"
            },
            "logo": {
                "type": "image",
                "label": "Logo",
                "view": "admin.onboarding.partials.logo-field",
                "name": "logo",
                "required": false
            },
            "primary_colors": {
                "type": "text",
                "label": "Primary colors",
                "view": "admin.onboarding.partials.colors-field",
                "name": "primary_colors",
                "required": false
            }
        };
    }

    static get format() {
        return {};
    }
}

export default Onboarding;
