// Generated by `php artisan make:js-models`. Edit the AppModel $properties, not this file.
import Model from "../vendor/juice/data/models/Model.mjs";

class Onboarding extends Model {
    static tableName = "onboardings";
    static primaryKey = "id";
    static timestamps = true;

    static get schema() {
        return {
        "user_id": {
            "type": "integer"
        },
        "step": {
            "type": "integer"
        },
        "dns_verified": {
            "type": "string"
        },
        "company_name": {
            "type": "string",
            "label": "Company Name"
        },
        "business_category": {
            "type": "string"
        },
        "region": {
            "type": "string"
        },
        "company_description": {
            "type": "string"
        },
        "brand_personality_voice": {
            "type": "string"
        },
        "brand_styles_to_avoid": {
            "type": "string"
        },
        "existing_brand_assets": {
            "type": "string"
        },
        "slogans": {
            "type": "string"
        },
        "logo": {
            "type": "string"
        },
        "ideal_customer": {
            "type": "string"
        },
        "region_scope": {
            "type": "string"
        },
        "primary_colors": {
            "type": "string"
        },
        "primary_color": {
            "type": "string"
        },
        "secondary_color": {
            "type": "string"
        },
        "logo_disk": {
            "type": "string"
        },
        "logo_path": {
            "type": "string"
        },
        "inspiration_domains": {
            "type": "string"
        },
        "suggested_sites": {
            "type": "string"
        },
        "generation_submission_id": {
            "type": "string"
        },
        "generation_remote_id": {
            "type": "string"
        },
        "generation_status": {
            "type": "string"
        },
        "generation_stage": {
            "type": "string"
        },
        "generation_error": {
            "type": "string"
        },
        "generation_started_at": {
            "type": "date",
            "label": "Generation Started At"
        }
    };
    }

    static get rules() {
        return {
        "company_name": "required|string|max:255",
        "business_category": "required|string|max:255",
        "region": "required|string|max:255",
        "company_description": "nullable|string|max:4000",
        "brand_personality_voice": "nullable|string|max:2000",
        "brand_styles_to_avoid": "nullable|string|max:2000",
        "existing_brand_assets": "nullable|string|max:2000",
        "slogans": "nullable|string|max:2000",
        "ideal_customer": "nullable|string|max:2000",
        "region_scope": "required|in:regional,national",
        "generation_started_at": "date|required"
    };
    }
}

export default Onboarding;
