// Generated by `php artisan make:js-models`. Edit the AppModel $properties, not this file.
import Model from "../vendor/juice/data/models/Model.mjs";

class PageSuggestion extends Model {
    static tableName = "page_suggestions";
    static primaryKey = "id";
    static timestamps = true;

    static get schema() {
        return {
        "user_id": {
            "type": "integer"
        },
        "parent_id": {
            "type": "integer"
        },
        "title": {
            "type": "string",
            "label": "Title"
        },
        "slug": {
            "type": "string",
            "label": "Slug"
        },
        "summary": {
            "type": "string",
            "label": "Summary"
        },
        "rationale": {
            "type": "string",
            "label": "Rationale"
        },
        "source_asset_ids": {
            "type": "string"
        },
        "suggested_copy": {
            "type": "string"
        },
        "status": {
            "type": "string",
            "label": "Status"
        },
        "sort_order": {
            "type": "integer"
        },
        "rejection_feedback": {
            "type": "string",
            "label": "Denial feedback"
        },
        "reviewed_at": {
            "type": "date",
            "label": "Reviewed At"
        },
        "ai_model": {
            "type": "string"
        },
        "ai_task": {
            "type": "string"
        },
        "ai_feedback": {
            "type": "string"
        },
        "ai_feedback_at": {
            "type": "date",
            "label": "Ai Feedback At"
        }
    };
    }

    static get rules() {
        return {
        "title": "required|string|max:255",
        "slug": "required|string|max:255",
        "summary": "required|string",
        "rationale": "nullable|string",
        "status": "required|string",
        "rejection_feedback": "nullable|string|max:2000",
        "reviewed_at": "date|required",
        "ai_feedback_at": "date|required"
    };
    }
}

export default PageSuggestion;
