[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm -F
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=300
user=www-data
autorestart=true
stopasgroup=true

[program:scheduler]
command=php /var/www/html/artisan schedule:work
user=www-data
autorestart=true
stopasgroup=true
