<?php

namespace Keystone\Toolkit\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Keystone\Toolkit\Models\AppModel;
use ReflectionClass;

/**
 * Generates juice JavaScript models from the app's AppModels. The same
 * `$properties` that drive fillable, casts, rules and the server forms become the
 * JS model's schema + rules, so the client model is a true mirror of the Laravel
 * one and validates with identical (Laravel-syntax) rules.
 */
class GenerateJsModels extends Command
{
    protected $signature = 'make:js-models {--path= : Output directory (defaults to config)}';

    protected $description = 'Generate juice JavaScript models from Laravel AppModels';

    public function handle(): int
    {
        $modelsPath = app_path('Models');

        if (! File::isDirectory($modelsPath)) {
            $this->error("No models directory at {$modelsPath}.");

            return self::FAILURE;
        }

        $outputPath = $this->option('path')
            ?: base_path((string) config('keystone.models.js_output', 'resources/js/models'));

        $baseImport = (string) config('keystone.models.js_base', '../vendor/juice/data/models/Model.mjs');

        File::ensureDirectoryExists($outputPath);

        $generated = 0;

        foreach (File::allFiles($modelsPath) as $file) {
            $class = 'App\\Models\\' . $file->getFilenameWithoutExtension();

            if (! class_exists($class)) {
                continue;
            }

            $reflection = new ReflectionClass($class);

            if ($reflection->isAbstract() || ! $reflection->isSubclassOf(AppModel::class)) {
                continue;
            }

            /** @var AppModel $model */
            $model = new $class;

            $jsName = $reflection->getShortName();
            $contents = $this->buildModel($jsName, $model, $baseImport);

            File::put($outputPath . DIRECTORY_SEPARATOR . $jsName . '.mjs', $contents);
            $this->info("Generated {$jsName}.mjs");
            $generated++;
        }

        $this->info("Done. {$generated} model(s) written to {$outputPath}.");

        return self::SUCCESS;
    }

    protected function buildModel(string $jsName, AppModel $model, string $baseImport): string
    {
        $properties = $model::getSchema()['properties'] ?? [];

        $schema = [];
        $rules = [];

        foreach ($properties as $property => $config) {
            $schema[$property] = ['type' => $this->jsType($config)];

            if (! empty($config['label'])) {
                $schema[$property]['label'] = $config['label'];
            }

            if (! empty($config['rules'])) {
                $rules[$property] = implode('|', (array) $config['rules']);
            }
        }

        $schemaJs = $this->indent(json_encode($schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        $rulesJs = $this->indent(json_encode((object) $rules, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        $timestamps = $model->usesTimestamps() ? 'true' : 'false';

        return <<<JS
// Generated by `php artisan make:js-models`. Edit the AppModel \$properties, not this file.
import Model from "{$baseImport}";

class {$jsName} extends Model {
    static tableName = "{$model->getTable()}";
    static primaryKey = "{$model->getKeyName()}";
    static timestamps = {$timestamps};

    static get schema() {
        return {$schemaJs};
    }

    static get rules() {
        return {$rulesJs};
    }
}

export default {$jsName};

JS;
    }

    /**
     * Map an AppModel property to a juice schema type.
     *
     * @param  array<string, mixed>  $config
     */
    protected function jsType(array $config): string
    {
        $type = $config['cast'] ?? $config['type'] ?? 'string';

        return match ($type) {
            'int', 'integer' => 'integer',
            'bool', 'boolean' => 'boolean',
            'array', 'json', 'object', 'collection' => 'json',
            'date', 'datetime', 'timestamp' => 'date',
            'float', 'double', 'decimal' => 'float',
            default => 'string',
        };
    }

    protected function indent(string $json): string
    {
        return str_replace("\n", "\n    ", $json);
    }
}
